name: CI

on:
  pull_request:
    types: [closed]
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: staging
          token: ${{ secrets.AT }}

      - name: Edit version in csproj
        run: sed -i 's/<Version>.*<\/Version>/<Version>1.0.5<\/Version>/g' test.txt
        shell: bash
        
      - name: Push
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add test.txt
          git commit -m "🖉 Update test.txt with ${GITHUB_REF#refs/*/}"
          git push
        shell: bash
